-- Script generated by Redgate Compare v1.48.1.2582


-- deployment: Creating users...
CREATE TABLE users (
    id int NOT NULL,
    username varchar(50) NOT NULL,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE users ADD PRIMARY KEY (id);


-- deployment: Creating products...
CREATE TABLE products (
    id int NOT NULL,
    product_name varchar(100) NOT NULL,
    price decimal(10,2) NOT NULL,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE products ADD PRIMARY KEY (id);


-- deployment: Creating orders...
CREATE TABLE orders (
    id int NOT NULL,
    user_id int NULL,
    order_date timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    total_amount decimal(10,2) NULL
);
ALTER TABLE orders ADD PRIMARY KEY (id);


-- deployment: Creating users.username...
CREATE UNIQUE INDEX username USING BTREE ON users(username);


-- deployment: Creating orders.user_id...
CREATE INDEX user_id USING BTREE ON orders(user_id);


-- deployment: Creating orders.orders_ibfk_1...
ALTER TABLE orders
    ADD CONSTRAINT orders_ibfk_1 FOREIGN KEY (user_id)
    REFERENCES users(id);

