-- Script generated by Redgate Compare v1.48.1.2582


-- deployment: Dropping users.status...
ALTER TABLE users DROP COLUMN status;


-- deployment: Dropping users.email...
ALTER TABLE users DROP COLUMN email;

