-- Script generated by Redgate Compare v1.48.1.2582


-- deployment: Creating users.status...
ALTER TABLE users ADD COLUMN status varchar(20) NULL DEFAULT 'active';


-- deployment: Creating users.email...
ALTER TABLE users ADD COLUMN email varchar(100) NULL;

